### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cameronstinson4** [ovidiumihaibelciug/gatsby-firebase-starter#2]
Hi, thanks so much for creating this 🔥template! Unfortunately, since your project does not have a license, it's not clear whether I have your permission to fork, clone, build, or use the code.

Could you please add a license file to clarify your position on this? I don't want to assume that you're making this project for open source, but I am interested in using it for some of my projects. I'll probably contribute some upstream if your intentions are to make this OSS.

Thanks,

**Comment by ovidiumihaibelciug** [comment]
Hey, Thank you for letting me know. I made this project for open source so feel free to use it as you wish. I added a license file (It's MIT).

Good luck on your projects!

**Comment by cameronstinson4** [comment]
That's perfect, thanks for the fast response!
